services:
  clash:
    image: ghcr.nju.edu.cn/bctjo/docker-clash:latest
    container_name: clash
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/root/.config/clash
    ports:
      - "9090:9090" # Portal
      - "9097:9097" # Dashboard
      - "7890:7890" # HTTP
      - "7891:7891" # SOCKS5
      - "7892:7892" # TPROXY
      - "7893:7893" # MIXED
    environment:
      PORTAL_PORT: "9090"        # Portal port (default 9090)
      DASH_PORT: "9097"          # Clash external-controller (default 9097)
      PORTAL_ADMIN_KEY: "your_password"       # Portal basic auth password
      # CLASH_HTTP_PORT: "7890"    # HTTP proxy port (default 7890)
      # CLASH_SOCKS_PORT: "7891"   # SOCKS5 proxy port (default 7891)
      # CLASH_TPROXY_PORT: "7892"  # TPROXY port (default 7892)
      # CLASH_MIXED_PORT: "7893"   # MIXED port (default 7893)