server {
  listen __PORTAL_PORT__;
  server_name _;

  root /opt/portal;
  index index.html;

  # Convert auth challenge response to 403 so browser won't show native basic auth dialog.
  error_page 401 = @portal_auth_forbidden;
  location @portal_auth_forbidden {
    internal;
    default_type application/json;
    add_header Cache-Control "no-store" always;
    return 403 '{"error":"unauthorized"}';
  }

  location = /status.json {
    add_header Cache-Control "no-store";
  }

  location = /subscription-info.json {
    add_header Cache-Control "no-store";
  }

  location = /subscription-validate.json {
    add_header Cache-Control "no-store";
  }

  location = /latency-browser.json {
    add_header Cache-Control "no-store";
  }

  location = /latency-router.json {
    add_header Cache-Control "no-store";
  }

  location = /settings.json {
    add_header Cache-Control "no-store";
    __PORTAL_AUTH__
    client_max_body_size 2k;
    dav_methods PUT;
    create_full_put_path on;
    access_log off;
    limit_except GET PUT { deny all; }
  }

  location = /subscriptions.json {
    add_header Cache-Control "no-store";
    __PORTAL_AUTH__
    client_max_body_size 16k;
    dav_methods PUT;
    create_full_put_path on;
    access_log off;
    limit_except GET PUT { deny all; }
  }

  location = /subscription-validate {
    add_header Cache-Control "no-store";
    __PORTAL_AUTH__
    client_max_body_size 4k;
    dav_methods PUT;
    create_full_put_path on;
    access_log off;
    limit_except PUT { deny all; }
  }

  location = /update {
    __PORTAL_AUTH__
    client_max_body_size 1k;
    dav_methods PUT;
    create_full_put_path on;
    access_log off;
    limit_except PUT { deny all; }
  }

  location = /latency-browser-refresh {
    __PORTAL_AUTH__
    client_max_body_size 1k;
    dav_methods PUT;
    create_full_put_path on;
    access_log off;
    limit_except PUT { deny all; }
  }

  location = /latency-router-refresh {
    __PORTAL_AUTH__
    client_max_body_size 1k;
    dav_methods PUT;
    create_full_put_path on;
    access_log off;
    limit_except PUT { deny all; }
  }

  location / {
    try_files $uri /index.html;
  }
}
